### ISSUE TITLE
An error about 'MultiPolygon' object is not iterable

### ISSUE THREAD

**Issue by Shuaichen-He** [Clarmy/cnmaps-doc#8]
Hi,
I followed the ”Read The Docs: cnmaps“ to run example code but this issue coming out, could you please help me ?
<img width="1252" alt="截屏2023-07-31 15 45 43" src="https://github.com/cnmetlab/cnmaps-doc/assets/85821954/abaafdc4-9adc-4895-8383-10cf9fbfa9df">

**Comment by Clarmy** [comment]
try: `$ pip install shapely==1.8.5`

**Comment by Shuaichen-He** [comment]
It's work! Thanks a lot~🌸
